/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

val vrsn = project.file("VERSION").readText().trim();
project.version = vrsn.toString();

tasks.register<Jar>("sourceJar") {
    archiveClassifier.set("sources")
    from(sourceSets.main.get().allSource)
}

plugins {
    // Apply the java-library plugin for API and implementation separation.
    id("java-library")
    id("edu.wpi.first.GradleRIO") version "2024.3.2"
    id("maven-publish")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    api("edu.wpi.first.wpilibj:wpilibj-java:2024.3.2")
    api("edu.wpi.first.wpiutil:wpiutil-java:2024.3.2")
    api("org.tomlj:tomlj:1.1.1")

    // Test imports
    testImplementation("edu.wpi.first.wpilibj:wpilibj-java:2024.3.2")
    testImplementation("edu.wpi.first.wpiutil:wpiutil-java:2024.3.2")
    testImplementation("org.tomlj:tomlj:1.1.1")
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter (JUnit 5) test framework
            useJUnitJupiter()
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/frc4206/battleaid")
            credentials {
                username = project.findProperty("gpr.user") as String? ?: System.getenv("USERNAME")
                password = project.findProperty("gpr.key") as String? ?: System.getenv("TOKEN")
            }
        }
    }
    publications {
        register<MavenPublication>("gpr"){
            groupId = "org.team4206"
            from(components["java"])
            artifact(tasks["sourceJar"])
        }
    }
}
